### PR TITLE
[Stability][UX] 修复课表待选框、导出白屏与 iOS 长后台恢复

### LINKED ISSUE #860: [Schedule] 双节空白待选框纵向漂移，未对齐真实课节虚线
## TL;DR

课表空白区第一次点击生成的双节虚线待选框，越靠下越与真实课节边界错位；真机截图中第 5–6 节待选框整体偏下，并超出对应虚线范围。

## 问题/需求描述

2026-09-19 iPhone 真机回归发现：点击周六第 5–6 节空白区域后，生成的“5–6”虚线待选框没有严格覆盖第 5、6 节的视觉区域，而是整体向下漂移。该框是两段式空白创建的第一阶段反馈，如果与课节虚线不一致，会让用户误判实际添加时段。

## 当前行为

基于最新 main 代码阅读：

- `apps/client/src/features/schedule/components/ScheduleGrid.vue:200` 的待选框位置来自 `intervalToGridRect(...)` 百分比坐标。
- 待选框节点位于 `.day-column` 内（约 381–383 行）。
- `.day-column` 只保证 `min-height: calc(var(--slot-height) * 11)`（约 638 行），实际高度可被布局拉伸。
- 同文件事件层为避免纵向漂移，明确把绘制层高度锁定为 `calc(var(--slot-height) * 11)`（约 698 行）。

截图现象与“百分比坐标相对于被拉高容器计算”一致：中下段偏差更明显。

## 期望行为

- 双节待选框的上边界、下边界应与课程网格中对应课节的视觉边界一致。
- 1–2、3–4、5–6、7–8、9–10 以及第 11 节都不应因屏幕高度或父容器拉伸产生累计漂移。
- 暗色/浅色模式都保持现有虚线视觉与点击语义。

## 影响范围

| 文件 | 区域 | 当前状态 |
|------|------|---------|
| `apps/client/src/features/schedule/components/ScheduleGrid.vue` | `blankSelectionStyle`、待选框节点、day/event layer 几何 | 待选框百分比参照容器与真实 11 节绘制层不完全同源 |
| `apps/client/src/features/schedule/utils/timeGeometry.ts` | 时间→网格坐标 | 为真实时间映射提供百分比几何 |
| `apps/client/src/features/schedule/utils/blankSelection.ts` | 双节吸附 | 选中的节次本身正确 |

## 触发/复现方式

1. iPhone 打开课表页，选择当前周。
2. 点击周六第 5–6 节空白区域一次。
3. 观察“5–6”虚线待选框与第 5、6 节背景虚线边界。
4. 对照点击 1–2、7–8、9–10，观察纵向偏差随位置变化。

## 验收标准

- [ ] 1–2 / 3–4 / 5–6 / 7–8 / 9–10 待选框均严格落在对应课节视觉范围
- [ ] 第 11 节单节选择位置正确
- [ ] 不同视口高度下无累计纵向漂移
- [ ] 第二次点击确认逻辑不受影响
- [ ] 有针对该坐标契约的自动化回归测试

## 关联

- Parent: #859
- 来源：#857 / #858 两段式空白创建

### LINKED ISSUE #861: [Schedule][i18n] 视图显示“都有”改为“全部”
## TL;DR

课表工具“视图显示”的第一项当前中文为“都有”，语气偏口语；统一改为更正式、清晰的“全部”。

## 问题/需求描述

2026-09-19 真机回归确认，“视图显示”三段选项当前显示为“都有 / 课表 / 日程”。其中“都有”与设置页整体产品文案风格不一致，用户要求改成“全部”。

## 当前行为

- `apps/client/src/utils/i18n/messages/zh-CN.ts:597`：`schedule.viewMode.all` 当前值为 `都有`。
- English 已为 `All`；日本語已为 `すべて`。
- 功能语义正确，仅简体中文展示文案需要调整。

## 期望行为

简体中文下显示“全部 / 课表 / 日程”，且持久化 key、筛选逻辑和其他语言不受影响。

## 影响范围

涉及模块：课表工具 → 视图显示 → i18n 文案。

## 触发/复现方式

1. 简体中文打开课表。
2. 打开左上角课表工具。
3. 查看“视图显示”第一项。

## 验收标准

- [ ] 简体中文显示“全部”而非“都有”
- [ ] English / 日本語现有文案不回归
- [ ] 视图筛选 key 与持久化数据不变化
- [ ] i18n key parity / coverage 测试通过

## 关联

- Parent: #859
- 来源：#856 / #858 视图显示

### LINKED ISSUE #862: [Me] 开源说明感谢文案泄漏 <strong> 标签
## TL;DR

“我的 → 开源说明”中感谢文案直接显示 `<strong>...</strong>` 字样，没有出现预期的粗体强调，属于用户可见的富文本渲染错误。

## 问题/需求描述

2026-09-19 iPhone 截图中，“感谢原 `<strong>Mini湖工</strong>` 小程序的开发者…”与“感谢开发者的 `<strong>朋友们和舍友们</strong>` …”把 HTML 标签原样展示。该弹窗本应是对开源来源与贡献者的正式说明，泄漏标签会明显降低完成度。

## 当前行为

基于最新 main：

- `apps/client/src/utils/i18n/messages/zh-CN.ts:2934-2935`（以及 en/ja 对应 key）把 `<strong>` 标签直接存入翻译字符串。
- `apps/client/src/components/MeView.vue:543-544` 使用普通 `{{ t(...) }}` 文本插值渲染这些字符串。
- Vue 文本插值会转义 HTML，因此标签按字面文本显示。

## 期望行为

- 用户只看到自然语言和正确的强调样式，不看到任何 HTML 标签字面量。
- 简体中文、English、日本語行为一致。
- 不降低现有内容安全边界，不把不受控翻译内容变成任意 HTML 注入面。

## 影响范围

| 文件 | 区域 | 当前状态 |
|------|------|---------|
| `apps/client/src/components/MeView.vue` | 开源说明感谢区 | 普通文本插值 |
| `apps/client/src/utils/i18n/messages/{zh-CN,en,ja}.ts` | `me.opensource.thanks*` | 翻译值含 HTML 标签 |

## 触发/复现方式

1. 打开“我的”。
2. 点击“开源说明”。
3. 查看感谢区前两行。
4. 可见 `<strong>` 与 `</strong>` 字符。

## 验收标准

- [ ] 三种语言均不显示 `<strong>` / `</strong>` 字面量
- [ ] 需要强调的名称/角色仍有明确视觉强调
- [ ] 不引入对任意 i18n HTML 的无约束渲染
- [ ] 对应组件测试覆盖

## 关联

- Parent: #859

### LINKED ISSUE #863: [Export Center][P0] 从“我的”进入导出中心直接白屏
## TL;DR

从“我的”点击“导出中心”后页面会直接白屏；最新 main 中存在可在首次渲染路径触发的 computed ref 使用错误，应作为高优先级运行时崩溃修复。

## 问题/需求描述

用户在 iOS 真机上通过“我的 → 导出中心”进入时，页面突然变为白屏，无法继续操作。导出中心属于已发布入口，进入页面本身不应因为初始化计算抛出未捕获异常。

## 当前行为

基于最新 main 代码阅读：

- `apps/client/src/components/ExportCenterView.vue:55` 将 `moduleGroups` 定义为 `computed(...)`。
- `apps/client/src/components/ExportCenterView.vue:88-93` 创建 `moduleMap` 时，在脚本上下文直接执行 `moduleGroups.forEach(...)`。
- Vue computed 在脚本中是 Ref，不会像模板表达式那样自动解包，因此该路径不是数组 `forEach`。
- `moduleMap` 又会被首屏 computed（如 `requiresSemester`、`selectedModuleMetas`）读取，异常可在页面初始化阶段出现并导致视图白屏。

## 期望行为

- 从“我的”进入导出中心稳定渲染首屏。
- 导出中心初始化阶段不存在未捕获异常。
- 学期加载失败、无网络、无缓存时也应该显示可理解的错误/空态，而不是整页白屏。

## 影响范围

| 文件 | 区域 | 当前状态 |
|------|------|---------|
| `apps/client/src/components/ExportCenterView.vue` | `moduleGroups` / `moduleMap` / 首屏 computed | 初始化路径存在 Ref/数组语义错误 |
| `apps/client/src/app/viewRegistry.ts` | `export_center` 异步视图 | 路由本身已注册 |
| `apps/client/src/components/MeView.vue` | 导出中心入口 | 发出 `navigate: export_center` |

## 触发/复现方式

1. 登录后打开“我的”。
2. 点击“导出中心”。
3. 观察页面是否白屏；记录 JS console/崩溃捕获中的首个异常。

## 验收标准

- [ ] “我的 → 导出中心”连续进入/返回至少 5 次均正常
- [ ] 首屏无 `forEach is not a function` 等未捕获异常
- [ ] 无网络/学期请求失败时页面仍能渲染错误提示
- [ ] 补充能够在测试环境捕获该初始化回归的测试
- [ ] typecheck / production build 通过

## 关联

- Parent: #859
- 近期导出日程扩展：#853

### PR DESCRIPTION
**Pull request by superdaobo**
## Summary

This PR closes the 2026-09-19 iPhone regression batch tracked by #859.

- Fixes the two-stage schedule blank-selection overlay drifting below real period boundaries by giving percentage geometry a fixed 11-period positioning layer.
- Renames the Simplified Chinese schedule view option from “都有” to the more formal “全部”.
- Fixes literal `<strong>` leakage in “我的 → 开源说明” without introducing `v-html`; emphasis is now structural template markup with plain i18n fragments.
- Fixes “我的 → 导出中心” white-screen initialization crash caused by iterating a computed ref without `.value`.
- Hardens Tauri iOS long-background recovery: native window-focus signal supplements WebView lifecycle events, long-idle iOS resumes soft-remount the current view, stale `home-scroll-restoring` interaction locks are cleared, transition-root health checks support strict mode, and resume decisions are recorded through the existing runtime debug-log bridge.

### Schedule selection drift (#860)
`blankSelectionStyle()` returns percentage geometry, but the selection element was positioned directly against `.day-column`, whose actual height can exceed the fixed 11-period canvas. Existing event cards already avoid this by positioning inside a fixed `11 × --slot-height` layer.

### Export Center blank page (#863)
`moduleGroups` is a Vue `computed()` ref, while `moduleMap` called `moduleGroups.forEach(...)` in script context. Script refs are not auto-unwrapped, so first render could throw `moduleGroups.forEach is not a function`.

### iOS long-background recovery (#864)
The existing recovery logic could miss a visible-but-noninteractive WKWebView: DOM nodes may remain geometrically healthy, `document.hidden` can be stale after a long freeze, and a frozen home-scroll restore state can leave `pointer-events: none`. Tauri iOS also did not have the Capacitor `appStateChange` signal.

This PR materially hardens those recovery paths. A true native-process crash/WebContent termination still requires TestFlight/Xcode device crash evidence to prove its final native cause; the new lifecycle breadcrumbs make that distinction easier on the next TestFlight validation.

## Validation

- Targeted regression suite: **6 files / 36 tests passed**
- Full Vitest CI suite: **passed** with `--maxWorkers=2`
- `pnpm run typecheck`: passed
- `pnpm run build`: passed
- Strict CSP bundle guard: passed
- Frontend safety guard: passed
- Design-token guard: passed
- Architecture guards: passed
- Dist-boundary guard: passed
- `git diff --check`: passed

### Known pre-existing debt

`check_god_files.mjs` still reports the existing #805 debt because the zh-CN/en/ja i18n dictionaries already exceed the 1000-line god-file threshold. The normal architecture guards and all validation above pass; this PR does not expand scope into that unrelated dictionary refactor.

## Issues

Refs #859
Closes #860
Closes #861
Closes #862
Closes #863
Refs #864

### CODE REVIEW

**Comment by superdaobo** [comment]
## Self-review

Completed a final diff review after CI.

- Scope is limited to the five #859 regressions plus their regression tests; PR contains exactly the expected 15 source/test files.
- #860 positioning fix now uses a fixed 11-period containing layer, matching the geometry basis already used by the event layer.
- #862 deliberately avoids `v-html`; emphasis uses real `<strong>` template nodes with plain i18n fragments.
- #863 is the minimal computed-ref correction (`moduleGroups.value`) with a source-level initialization regression test.
- #864 recovery path has bounded behavior: short resumes keep the existing lightweight path; iOS long-idle resumes soft-remount, hard reload remains subject to the existing 15-minute/rate/count guards, and Tauri native focus is cleaned up on dispose.
- Transition-health review also caught and fixed a pre-existing blind spot: Vue transition classes can be on `.view-transition-root` itself, so health checks now inspect both the root and descendants.

Validation is green locally and on GitHub: PR Gate, test-frontend, secret-guard and JavaScript/TypeScript CodeQL all completed successfully. No blocking findings remain in code review.

#864 intentionally remains open after this PR because a true native iOS process/WebContent crash cannot be proven fixed by JS/unit tests alone. The code-side recovery regression is fixed here; the issue should be closed only after a TestFlight build completes the documented 10/15/30-minute real-device resume matrix and crash-log check. Parent #859 remains open for the same reason.
